### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by Ninerian** [rollup/rollup-plugin-strip#14]
Would you be so kind and create a new release for this plugin, as the 1.1.1 doesn't include the fixes for the async syntax.

**Comment by eventualbuddha** [comment]
If @Rich-Harris wants to give me access I'll do the release.

**Comment by emartinpi** [comment]
Yes please, I need the new release as well.

**Comment by Rich-Harris** [comment]
Apologies, missed this until now. Released 1.2.0 — thanks for the prod

**Comment by Rich-Harris** [comment]
I've added this repo to @rollup/collaborators, and added @eventualbuddha as an owner of the npm package so that I'm not a blocker next time
