### ISSUE TITLE
Remove console in async function block

### ISSUE THREAD

**Issue by FlandreDaisuki** [rollup/rollup-plugin-strip#8]
I got `SyntaxError: Unexpected token` when I want to remove console in async function block.

Code:
```
foo( 123 );
async function fn(){
	console.log( 'a' );
}
console.error( 'b' );
bar( 789 );
```

Expect:
```
foo( 123 );
async function fn(){
}
bar( 789 );
```

or

```
foo( 123 );
async function fn(){}
bar( 789 );
```

But:
```
SyntaxError: Unexpected token (2:6)
```

Node: v8.9.0
rollup-plugin-strip: v1.1.1

**Comment by dekdevy** [comment]
Is there any temp fix until the pull is accepted?

**Comment by eventualbuddha** [comment]
I don't have publish access, so @Rich-Harris will have to do it (or give me access).

**Comment by dekdevy** [comment]
bump :/
